work_dir: ./work_dir/woC/ntu/xview/agcn_joint
model_saved_name: ./runs/ntu_cv_agcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/winter/2s-AGCN/ntu/xview/train_data_joint.npy
  label_path: /home/winter/2s-AGCN/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/winter/2s-AGCN/ntu/xview/val_data_joint.npy
  label_path: /home/winter/2s-AGCN/ntu/xview/val_label.pkl

# model
model: model.agcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.00015
base_lr: 0.01
step: [10, 20, 30, 40, 50]

# training
device: [0]
batch_size: 32
test_batch_size: 30
num_epoch: 60
nesterov: True
