base_lr: 0.01
batch_size: 256
config: ./config/nturgbd-cross-subject/test_joint.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ./runs/ntu_cs_agcn_test_joint
nesterov: false
num_epoch: 80
num_worker: 8
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: test
print_log: true
save_interval: 2
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 400
test_feeder_args:
  data_path: /home/winter/2s-AGCN/data/ntu/xsub/val_data_joint.npy
  debug: false
  label_path: /home/winter/2s-AGCN/data/ntu/xsub/val_label.pkl
train_feeder_args: {}
warm_up_epoch: 0
weight_decay: 0.0005
weights: ./backup_weight/full_version_weight/ntu_cs_agcn_joint-49-62600.pt
work_dir: ./work_dir/ntu/xsub/agcn_test_joint
