work_dir: 2s-AGCN-2/work_dir/woC/ntu/xview/agcn_joint
model_saved_name: 2s-AGCN-2/runs/dcp0cv9xdcp0tsp75-0
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: 2s-AGCN-2/data/ntu/xview/train_data_joint.npy
  label_path: 2s-AGCN-2/data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: 2s-AGCN-2/data/ntu/xview/val_data_joint.npy
  label_path: 2s-AGCN-2/data/ntu/xview/val_label.pkl

# model
model: model.agcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
# step: [15, 25, 40]
step: [12, 24, 34]



# training
# device: [0, 1, 2]
device: [2]
batch_size: 24
test_batch_size: 200
num_epoch: 44
nesterov: True
