# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: 2s-AGCN/data/ntu/xview/val_data_joint.npy
  label_path: 2s-AGCN/data/ntu/xview/val_label.pkl
  debug: False

# model
model: model.agcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: [0]
test_batch_size: 200
weights: 2s-AGCN/backup_weight/dcp0-40-42845.pt

work_dir: 2s-AGCN/work_dir/ntu/xview/agcn_test_joint
model_saved_name: 2s-AGCN/runs/ntu_cv_agcn_test_joint
save_score: True